# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 302)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(530, 190, 140, 40))
        self.startBtn.setObjectName("startBtn")
        self.updateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.updateBtn.setGeometry(QtCore.QRect(370, 190, 140, 40))
        self.updateBtn.setObjectName("updateBtn")
        self.chooseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.chooseBtn.setGeometry(QtCore.QRect(200, 190, 140, 40))
        self.chooseBtn.setObjectName("chooseBtn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 45, 40))
        self.label_3.setObjectName("label_3")
        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setGeometry(QtCore.QRect(100, 120, 571, 40))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.portSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.portSpinBox.setGeometry(QtCore.QRect(100, 70, 171, 40))
        self.portSpinBox.setMinimum(1)
        self.portSpinBox.setMaximum(65536)
        self.portSpinBox.setProperty("value", 3000)
        self.portSpinBox.setObjectName("portSpinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(31, 61, 45, 40))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 45, 40))
        self.label_2.setObjectName("label_2")
        self.hostLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hostLineEdit.setGeometry(QtCore.QRect(100, 20, 171, 40))
        self.hostLineEdit.setObjectName("hostLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Go File 启动器"))
        self.startBtn.setText(_translate("MainWindow", "启动"))
        self.updateBtn.setText(_translate("MainWindow", "更新"))
        self.chooseBtn.setText(_translate("MainWindow", "选择路径"))
        self.label_3.setText(_translate("MainWindow", "路径："))
        self.label.setText(_translate("MainWindow", "端口："))
        self.label_2.setText(_translate("MainWindow", "地址："))
        self.hostLineEdit.setText(_translate("MainWindow", "localhost"))
